export const DEMO_PROFILE = {
  id: 'demo-user-id',
  email: 'demo@northeastern.edu',
  first_name: 'Demo',
  last_name: 'User',
  campus: 'Boston',
  avatar_url: null,
  is_moderator: false,
  is_owner: false,
  is_banned: false,
};

export const DEMO_LISTINGS = [
  {
    item_id: 'demo-1',
    title: 'Lost: Black AirPods Max Case',
    description: 'Lost near Snell Library on Friday afternoon. Has a small red sticker on the back. Please reach out if found!',
    listing_type: 'lost',
    resolved: false,
    found_at: 'Snell Library, 2nd floor study area',
    locations: { name: 'Snell Library', campus: 'boston', coordinates: null },
    lat: 42.3398,
    lng: -71.0892,
    image_url: '/demo/demo-1.jpg',
    date: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    poster_id: 'demo-other-1',
    poster_name: 'Marcus T.',
    category: 'Electronics',
    importance: 3,
  },
  {
    item_id: 'demo-2',
    title: 'Found: Black Hydro Flask (32oz)',
    description: 'Found on a bench outside Marino Center Wednesday morning. Has a few stickers on it — mountain and a wave.',
    listing_type: 'found',
    resolved: false,
    found_at: 'Marino Center, outdoor benches',
    locations: { name: 'Marino Center', campus: 'boston', coordinates: null },
    lat: 42.3374,
    lng: -71.0882,
    image_url: '/demo/demo-2.jpg',
    date: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    poster_id: 'demo-other-2',
    poster_name: 'Priya S.',
    category: 'Other',
    importance: 2,
  },
  {
    item_id: 'demo-3',
    title: 'Lost: Northeastern Student ID',
    description: 'Dropped somewhere between Columbus Ave and the Curry Student Center Tuesday afternoon.',
    listing_type: 'lost',
    resolved: false,
    found_at: 'Curry Student Center area',
    locations: { name: 'Curry Student Center', campus: 'boston', coordinates: null },
    lat: 42.3388,
    lng: -71.0874,
    image_url: '/demo/demo-3.png',
    date: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    poster_id: 'demo-other-3',
    poster_name: 'Zoe L.',
    category: 'Husky Card',
    importance: 3,
  },
  {
    item_id: 'demo-4',
    title: 'Found: MacBook 67W USB-C Charger',
    description: 'Left in Ryder Hall Room 101 after the 2pm CS lecture. White cable, Apple brick.',
    listing_type: 'found',
    resolved: false,
    found_at: 'Ryder Hall, Room 101',
    locations: { name: 'Ryder Hall', campus: 'boston', coordinates: null },
    lat: 42.3392,
    lng: -71.0888,
    image_url: '/demo/demo-4.jpeg',
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    poster_id: 'demo-other-4',
    poster_name: 'Dante R.',
    category: 'Electronics',
    importance: 2,
  },
  {
    item_id: 'demo-5',
    title: 'Lost: Gray North Face Backpack',
    description: 'Think I left it on the 39 bus Thursday evening. Has a laptop, charger, and two notebooks inside.',
    listing_type: 'lost',
    resolved: false,
    found_at: 'Route 39 bus / Ruggles Station',
    locations: { name: 'Ruggles Station', campus: 'boston', coordinates: null },
    lat: 42.3361,
    lng: -71.0877,
    image_url: '/demo/demo-5.jpg',
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    poster_id: 'demo-other-5',
    poster_name: 'Aaliyah W.',
    category: 'Bag',
    importance: 3,
  },
  {
    item_id: 'demo-6',
    title: 'Found: Silver Volkswagen Key Ring',
    description: 'Found on the floor near the 3rd floor printer in Hayden Hall. Silver VW key ring with 2 keys.',
    listing_type: 'found',
    resolved: false,
    found_at: 'Hayden Hall, 3rd floor',
    locations: { name: 'Hayden Hall', campus: 'boston', coordinates: null },
    lat: 42.3385,
    lng: -71.0896,
    image_url: '/demo/demo-6.jpeg',
    date: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    poster_id: 'demo-other-6',
    poster_name: 'Liam C.',
    category: 'Keys',
    importance: 2,
  },
];

const DEMO_OTHER_PROFILE = {
  id: 'demo-other-1',
  first_name: 'Marcus',
  last_name: 'T.',
  campus: 'Boston',
  avatar_url: null,
};

export const DEMO_CONVERSATIONS = [
  {
    id: 'demo-convo-1',
    participant_1: 'demo-user-id',
    participant_2: 'demo-other-1',
    listing_id: 'demo-1',
    created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
];

export const DEMO_PROFILES = {
  'demo-other-1': DEMO_OTHER_PROFILE,
};

export const DEMO_LISTINGS_MAP = Object.fromEntries(DEMO_LISTINGS.map(l => [l.item_id, l]));

export const DEMO_UNREAD_COUNTS = {};

export const DEMO_MESSAGES = {
  'demo-convo-1': [
    {
      id: 'demo-msg-1',
      conversation_id: 'demo-convo-1',
      sender_id: 'demo-user-id',
      content: "Hey Marcus! I think I found your AirPods Max case near Snell Library. Is it black with a small red sticker on the back?",
      created_at: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    },
    {
      id: 'demo-msg-2',
      conversation_id: 'demo-convo-1',
      sender_id: 'demo-other-1',
      content: "Yes!! That's definitely mine, thank you so much for reaching out!",
      created_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    },
    {
      id: 'demo-msg-3',
      conversation_id: 'demo-convo-1',
      sender_id: 'demo-user-id',
      content: "No problem! I'll hand them to you at the Lost & Found desk in Curry Student Center.",
      created_at: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    },
    {
      id: 'demo-msg-4',
      conversation_id: 'demo-convo-1',
      sender_id: 'demo-other-1',
      content: "Perfect, heading over there now. Really appreciate it!",
      created_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    },
  ],
};
